### ISSUE TITLE
Extracting type examples from endpoint examples

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern-openapi#51]
Currently if someone specifies an endpoint example using fern, then we generate that into an OpenAPI endpoint example as well. However, a lot of documentation like `Stoplight` benefit from having examples for each type. Couple of options here: 

1. **Force the user to create type + endpoint examples in the fern definition**. This option offloads the workload to the user while keeping the generator quite simple. However, it is verbose to force the user to have to specify examples for both type & endpoint and results in a messy fern definition.

2. **If no type examples are provided, use the examples from the endpoint as a fallback.** This puts more work on the generator since it has to do complex logic of figuring out if the endpoint examples contain examples of that type, however it results in us generating the best quality Open API Spec from a given fern definition. One thing that needs to be figured out here is what endpoint example is used when there are multiple endpoint examples that contain information for a given type.

**Comment by dsinghvi** [comment]
I have currently implemented some version of 2, but we can obviously revert if we decide this isn't the best course of action.

**Comment by zachkirsch** [comment]
I think that’s an okay stopgap if it’s solving an important need rn but I think named examples that you can reference is a better solution. Thoughts:
1. This is the first time we’d be adding any sort of dependency of types on endpoints. Right now all “type” features exist independently of endpoints. Introduces complexity for the user imo
2. Type examples might not make sense in a vacuum. eg I often use “missing-id” as a UserId example to demonstrate a 404, which would be a weird example to show for UserId
3. For commonly used types, you might end up with a ton of examples for that type, which may not be what you want. The example generation is kind of “magic” and there’s no way to control that.

**Comment by dsinghvi** [comment]
So currently the way it works is if there are no existing type examples then it looks for one in the endpoint. It also only looks from endpoint examples that are successful (ignoring examples of errored calls). Basically solves 2 and 3 of your points. 

I think referenced examples work but my point was lets say for some reason you don't have a type example but you do have an endpoint example, in that case it seems strictly better for us to fallback to the endpoint to get your example? The generated open api spec with the type example will be higher quality than one without one.

**Comment by zachkirsch** [comment]
> I think that’s an okay stopgap if it’s solving an important need rn but I think named examples that you can reference is a better solution.

To clarify, are you comparing "type example inference" to referenced examples or to the status quo? Hard for me to imagine that inference > referenced examples, but happy to be wrong.

FWIW I think the points from my first comment stand:
1. This is the first time we’d be adding any sort of dependency of types on endpoints.
2. Type examples might not make sense in a vacuum. eg I often use “missing-id” as a UserId example to demonstrate a 404, which would be a weird example to show for UserId.
  a. I saw your reply of "we can ignore error endpoints examples to get around this." I don't think this really addresses the problem, feels very possible to have 200 examples that still don't make sense in a vacuum. e.g. `user-without-first-name` to demonstrate a user example without the optional first name property. In general when it comes to inference, Fern will have less context and will inevitably make mistakes. At the very least there would need to be an extra config to disable the inference, which obv introduces more complexity.
3. For commonly used types, you might end up with a ton of examples for that type, which may not be what you want. 

It's hard for me to come up with an argument that inference is better than referenced examples. I guess it saves you a little time when you're writing the the Fern Definition? But only because you're thinking "I've learned about Fern example inference works and I know that i can leave out a type example here and Fern will infer it from my endpoints" which is complexity I'd love for our users not to think about.

> I think referenced examples work but my point was lets say for some reason you don't have a type example but you do have an endpoint example, in that case it seems strictly better for us to fallback to the endpoint to get your example? The generated open api spec with the type example will be higher quality than one without one.

I don't think this is reason enough to try to do it automatically. If a user wants a type example because they think that will make their docs better, then great - they should add one. If they don't want to duplicate the example - great, they should reference the example.

**Comment by dsinghvi** [comment]
I am saying that in either world (with referenced examples or without referenced examples) if you have a type w/o an example but an endpoint that contains an example with that type then the generate OpenAPI Spec is better quality if you interrogate the endpoint example. That is inevitably what I found myself doing in Stoplight when the type wasn't there in the first place - i was looking for endpoints that contained the type to see how its used. 

I kind of see what you're saying for 2 but don't really see what you are saying for 3. 
I think for 2 in general what I have seen is that the examples are representative and what you're saying is an edge case. 
For 3, my response was that we would use the type example if given and if not provided default to using what was used in the endpoint. So you aren't ever ending up with "many" examples, we are only talking about the case where there are no first-class types provided. 

> I don't think this is reason enough to try to do it automatically. If a user wants a type example because they think that will make their docs better, then great - they should add one. If they don't want to duplicate the example - great, they should reference the example.

So we felt the fern definition would be way too messy if we did this for Gigs but down to implement referenced examples and come back to this and see how we feel.
